name: CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
      
      - name: Tag index with current datetime
        run: "sed -i \"s/[[datetime]]/$NOW/g\" index.html"

      - name: SFTP Sync
        uses: swillner/sftp-sync-action@v1.0
        with:
          server: ${{ secrets.SFTP_SERVER }}
          user: ${{ secrets.SFTP_USER }}
          user_private_key: ${{ secrets.SFTP_PK }}
          remote: "/var/www/html-ar/"
          mirror_options: "--exclude-glob=.git*/ --verbose"

